// Writes src/strategies/registry.ts from the strategy files on disk, then
// anon-kit.schema.json from the registry. Both are committed build artifacts:
// add or remove a strategy file and rerun (bun run schema) — no hand edits.
//
// The registry must be regenerated before anything imports it, or a deleted
// strategy file would crash the import; hence the dynamic import below.

import { readdirSync } from "node:fs";

const NON_STRATEGY = ["index.ts", "types.ts", "registry.ts"];

const names = readdirSync("src/strategies")
  .filter(
    (f) =>
      f.endsWith(".ts") && !f.endsWith(".test.ts") && !NON_STRATEGY.includes(f),
  )
  .map((f) => f.slice(0, -".ts".length))
  .sort();

await Bun.write(
  "src/strategies/registry.ts",
  [
    "// Generated by bun run schema — do not edit. One entry per strategy file",
    "// in this directory; add or remove a file and rerun.",
    "",
    ...names.map((n) => `import { ${n} } from "./${n}";`),
    "",
    "export const STRATEGIES = {",
    ...names.map((n) => `  ${n},`),
    "};",
    "",
  ].join("\n"),
);
console.log(`Wrote src/strategies/registry.ts (${names.length} strategies)`);

// Imported only now, so it resolves against the registry just written.
const { buildMapSchema } = await import("../src/schema");

await Bun.write(
  "anon-kit.schema.json",
  JSON.stringify(buildMapSchema(), null, 2) + "\n",
);
console.log("Wrote anon-kit.schema.json");
