// Generated by bun run schema — do not edit. One entry per strategy file
// in this directory; add or remove a file and rerun.

import { date_shift } from "./date_shift";
import { email } from "./email";
import { first_name } from "./first_name";
import { follow_fk } from "./follow_fk";
import { hash_id } from "./hash_id";
import { keep } from "./keep";
import { last_name } from "./last_name";
import { phone } from "./phone";
import { redact } from "./redact";
import { scrub_text } from "./scrub_text";
import { zip3 } from "./zip3";

export const STRATEGIES = {
  date_shift,
  email,
  first_name,
  follow_fk,
  hash_id,
  keep,
  last_name,
  phone,
  redact,
  scrub_text,
  zip3,
};
