// Generated by bun run schema — do not edit. One entry per strategy file
// in this directory; add or remove a file and rerun.

import { date_shift } from "./date_shift.ts";
import { email } from "./email.ts";
import { first_name } from "./first_name.ts";
import { follow_fk } from "./follow_fk.ts";
import { hash_id } from "./hash_id.ts";
import { keep } from "./keep.ts";
import { last_name } from "./last_name.ts";
import { phone } from "./phone.ts";
import { redact } from "./redact.ts";
import { scrub_text } from "./scrub_text.ts";
import { zip3 } from "./zip3.ts";

export const STRATEGIES = {
  date_shift,
  email,
  first_name,
  follow_fk,
  hash_id,
  keep,
  last_name,
  phone,
  redact,
  scrub_text,
  zip3,
};
