// Pure core: map validation and SQL compilation. Everything here is
// (mapping, schema data) → data — no env, no database, no filesystem, no
// process.exit. The shells (init.ts, apply.ts) own all I/O, which is what
// keeps this module testable with hard-coded fixtures and no mocks.
//
// Strategy-specific behavior lives in the strategies/ registry; this module
// owns what is structural — drift checks, the two-pass mask plan, and the
// FK bookkeeping around the ID rewrite.

import {
  STRATEGIES,
  STRATEGY_NAMES,
  type ColumnRule,
  type Mapping,
} from "./strategies";
import { qualify, quoteIdent, quoteLiteral, type Column, type Fk } from "./lib";

const GENERATED_HEADER =
  "-- Generated by anon-kit apply — do not edit. Regenerate from anon-kit.json.";

const ruleFor = (
  mapping: Mapping,
  table: string,
  column: string,
): ColumnRule | undefined => mapping[table]?.[column];

// Strategy of the column rule.references points at; undefined = references
// missing or target not in the map, null = target mapped but undecided.
const refStrategy = (mapping: Mapping, rule: ColumnRule) => {
  if (rule.references === undefined) return undefined;
  const [ps, pt, pc] = rule.references.split(".");
  return ruleFor(mapping, `${ps}.${pt}`, pc ?? "")?.strategy;
};

// ---------------------------------------------------------------- validate

// Diffs the mapping against the live schema and checks every strategy's
// requirements. Returns the full error list — callers decide how to report.
export function validate(
  mapping: Mapping,
  columns: Column[],
  fks: Fk[],
): string[] {
  const errors: string[] = [];

  for (const c of columns) {
    const path = `${c.schema}.${c.table}.${c.column}`;
    const rule = ruleFor(mapping, `${c.schema}.${c.table}`, c.column);
    if (!rule) {
      errors.push(
        `live column not in mapping: ${path} — add it to anon-kit.json and choose a strategy`,
      );
      continue;
    }
    // The map's _pgType/_nullable are an init-written cache of these live
    // facts (for the IDE); live stays authoritative, stale is an error.
    if (rule._pgType !== c.pgType || rule._nullable !== c.nullable)
      errors.push(
        `stale schema facts on ${path} — set "_pgType": ${JSON.stringify(c.pgType)}, "_nullable": ${c.nullable}`,
      );
    if (rule.strategy === null) errors.push(`strategy not chosen: ${path}`);
  }
  for (const [table, cols] of Object.entries(mapping)) {
    for (const column of Object.keys(cols)) {
      if (
        !columns.some(
          (c) => `${c.schema}.${c.table}` === table && c.column === column,
        )
      )
        errors.push(`mapped column no longer exists: ${table}.${column}`);
    }
  }
  // Schema facts come from the live introspection, never the map.
  const live = new Map(
    columns.map((c) => [`${c.schema}.${c.table}.${c.column}`, c]),
  );

  for (const [table, cols] of Object.entries(mapping)) {
    for (const [column, rule] of Object.entries(cols)) {
      if (rule.strategy === null) continue; // reported above
      const strategy = STRATEGIES[rule.strategy];
      // Unknown strategies hard-fail here with the valid list; the registry
      // lookups in compile only backstop this with a throw.
      if (!strategy) {
        errors.push(
          `unknown strategy "${rule.strategy}" on ${table}.${column} — valid: ${STRATEGY_NAMES.join(", ")}`,
        );
        continue;
      }
      const liveCol = live.get(`${table}.${column}`);
      if (strategy.types && liveCol && !strategy.types.includes(liveCol.pgType))
        errors.push(
          `${rule.strategy} on ${table}.${column} needs ${strategy.types.join(" or ")}, column is ${liveCol.pgType}`,
        );
      errors.push(
        ...(strategy.validate?.({
          table,
          column,
          rule,
          liveCol,
          siblingColumns: Object.keys(cols),
          referencedStrategy: refStrategy(mapping, rule),
        }) ?? []),
      );
    }
  }

  // The ID rewrite is map-driven, so declared FK constraints must not be
  // missable: a constraint pointing at a hash_id column whose child column
  // isn't follow_fk would surface as an FK violation at COMMIT instead of a
  // clear error here.
  for (const f of fks) {
    const parentPath = `${f.parentSchema}.${f.parentTable}.${f.parentColumn}`;
    const parentRule = ruleFor(
      mapping,
      `${f.parentSchema}.${f.parentTable}`,
      f.parentColumn,
    );
    if (parentRule?.strategy !== "hash_id") continue;
    const child = ruleFor(
      mapping,
      `${f.childSchema}.${f.childTable}`,
      f.childColumn,
    );
    if (child?.strategy !== "follow_fk" || child.references !== parentPath)
      errors.push(
        `${f.childSchema}.${f.childTable}.${f.childColumn} (constraint ${f.name}) points at hashed ${parentPath} — set it to follow_fk with references "${parentPath}"`,
      );
  }

  return errors;
}

// ----------------------------------------------------------------- compile

const maskExpr = (column: string, rule: ColumnRule): string | null => {
  if (rule.strategy === null) throw new Error(`strategy not chosen: ${column}`);
  const strategy = STRATEGIES[rule.strategy];
  if (!strategy) throw new Error(`unknown strategy: ${rule.strategy}`);
  return strategy.expr && strategy.expr(quoteIdent(column), rule);
};

const mapTableName = (table: string, column: string) =>
  `_map_${(table + "_" + column).replaceAll(/\W/g, "_")}`;

// Columns rewritten in the ID pass: every follow_fk entry whose referenced
// column is hashed. Map-driven, so soft FKs (no constraint) rewrite too.
export function rewrittenFollowers(mapping: Mapping) {
  return Object.entries(mapping)
    .flatMap(([table, cols]) =>
      Object.entries(cols)
        .filter(([, r]) => r.strategy === "follow_fk")
        .map(([column, r]) => ({ table, column, references: r.references! })),
    )
    .filter((f) => {
      const [ps, pt, pc] = f.references.split(".");
      return ruleFor(mapping, `${ps}.${pt}`, pc ?? "")?.strategy === "hash_id";
    });
}

export function compileMask(mapping: Mapping, fks: Fk[]): string {
  const hashedColumns = Object.entries(mapping).flatMap(([table, cols]) =>
    Object.entries(cols)
      .filter(([, r]) => r.strategy === "hash_id")
      .map(([column]) => ({ table, column })),
  );
  const followers = rewrittenFollowers(mapping);

  // Declared constraints on hashed columns still need deferring for the rewrite
  const constraintFks: Fk[] = fks.filter((f) =>
    hashedColumns.some(
      (h) =>
        h.table === `${f.parentSchema}.${f.parentTable}` &&
        h.column === f.parentColumn,
    ),
  );
  const toDefer = constraintFks.filter((f) => !f.deferrable);

  const mask: string[] = [GENERATED_HEADER, "", "BEGIN;", ""];

  for (const f of toDefer) {
    mask.push(
      `ALTER TABLE ${quoteIdent(f.childSchema)}.${quoteIdent(f.childTable)} ALTER CONSTRAINT ${quoteIdent(f.name)} DEFERRABLE INITIALLY DEFERRED;`,
    );
  }
  if (constraintFks.length > 0) mask.push("SET CONSTRAINTS ALL DEFERRED;", "");

  // Pass 1: one UPDATE per table for the value strategies. Every expression
  // sees original row values (ID rewrite comes later), which is what keeps
  // date_shift deterministic across runs.
  for (const [table, cols] of Object.entries(mapping)) {
    const sets = Object.entries(cols)
      .map(([column, rule]) => ({ column, e: maskExpr(column, rule) }))
      .filter((s): s is { column: string; e: string } => s.e !== null);
    if (sets.length === 0) continue;
    mask.push(
      `UPDATE ${qualify(table)} SET`,
      sets
        .map(
          (s, i) =>
            `  ${quoteIdent(s.column)} = ${s.e}${i < sets.length - 1 ? "," : ";"}`,
        )
        .join("\n"),
      "",
    );
  }

  // Pass 2: ID rewrite. Old->new map per hashed column drives the PK and every
  // FK that references it, so joins keep resolving.
  for (const { table, column } of hashedColumns) {
    const mapName = mapTableName(table, column);
    const c = quoteIdent(column);
    mask.push(
      `CREATE TEMP TABLE ${mapName} AS`,
      `SELECT ${c} AS old_id, anon_kit.hash_id(${c}::text) AS new_id FROM ${qualify(table)};`,
      `CREATE INDEX ON ${mapName} (old_id);`,
      "",
      `UPDATE ${qualify(table)} t SET ${c} = m.new_id FROM ${mapName} m WHERE t.${c} = m.old_id;`,
    );
    for (const f of followers.filter(
      (f) => f.references === `${table}.${column}`,
    )) {
      mask.push(
        `UPDATE ${qualify(f.table)} t SET ${quoteIdent(f.column)} = m.new_id FROM ${mapName} m WHERE t.${quoteIdent(f.column)} = m.old_id;`,
      );
    }
    mask.push(`DROP TABLE ${mapName};`, "");
  }

  // ALTER TABLE is refused while deferred FK checks are queued — fire them now
  if (toDefer.length > 0) {
    mask.push("SET CONSTRAINTS ALL IMMEDIATE;", "");
    for (const f of toDefer) {
      mask.push(
        `ALTER TABLE ${quoteIdent(f.childSchema)}.${quoteIdent(f.childTable)} ALTER CONSTRAINT ${quoteIdent(f.name)} NOT DEFERRABLE;`,
      );
    }
    mask.push("");
  }
  mask.push("COMMIT;", "");

  return mask.join("\n");
}

// Leak checks derived from the mapping. Every row must return leaks = 0.
export function compileVerify(mapping: Mapping): {
  sql: string;
  checkCount: number;
} {
  const checks: string[] = [];
  const addCheck = (label: string, table: string, cond: string) =>
    checks.push(
      `SELECT ${quoteLiteral(label)} AS check_, count(*)::int AS leaks FROM ${qualify(table)} WHERE ${cond}`,
    );

  for (const [table, cols] of Object.entries(mapping)) {
    for (const [column, rule] of Object.entries(cols)) {
      if (rule.strategy === null)
        throw new Error(`strategy not chosen: ${table}.${column}`);
      const strategy = STRATEGIES[rule.strategy];
      if (!strategy) throw new Error(`unknown strategy: ${rule.strategy}`);
      for (const check of strategy.checks(quoteIdent(column), {
        rule,
        referencedStrategy: refStrategy(mapping, rule),
      }))
        addCheck(
          `${table}.${column} ${rule.strategy}${check.suffix ?? ""}`,
          table,
          check.cond,
        );
    }
  }

  return {
    sql: GENERATED_HEADER + "\n\n" + checks.join("\nUNION ALL\n") + ";\n",
    checkCount: checks.length,
  };
}

// ------------------------------------------------------------------ probes

// One no-op UPDATE per redact sentinel. WHERE false touches no rows, but
// Postgres still coerces the literal to the column's type at parse time —
// the same coercion the mask's UPDATE takes — so apply can fail an
// uncastable sentinel (say "abc" on an integer column) before anything is
// written. Redact-to-null needs no probe; validate owns the NOT NULL case.
export function compileProbes(
  mapping: Mapping,
): { table: string; column: string; sql: string }[] {
  return Object.entries(mapping).flatMap(([table, cols]) =>
    Object.entries(cols)
      .filter(
        ([, r]) => r.strategy === "redact" && typeof r.sentinel === "string",
      )
      .map(([column, r]) => ({
        table,
        column,
        sql: `UPDATE ${qualify(table)} SET ${quoteIdent(column)} = ${quoteLiteral(r.sentinel!)} WHERE false`,
      })),
  );
}

// -------------------------------------------------------------------- init

// init's scaffold: every column listed, defaulted to "keep". FK columns are
// prefilled with follow_fk (they inherit whatever the referenced column
// decides, so there's nothing to choose).
export function defaultMap(columns: Column[], fks: Fk[]): Mapping {
  const mapping: Mapping = {};
  for (const c of columns) {
    const table = `${c.schema}.${c.table}`;
    const fk = fks.find(
      (f) =>
        f.childSchema === c.schema &&
        f.childTable === c.table &&
        f.childColumn === c.column,
    );
    const rule: ColumnRule = fk
      ? {
          strategy: "follow_fk",
          references: `${fk.parentSchema}.${fk.parentTable}.${fk.parentColumn}`,
          _pgType: c.pgType,
          _nullable: c.nullable,
        }
      : { strategy: "keep", _pgType: c.pgType, _nullable: c.nullable };
    (mapping[table] ??= {})[c.column] = rule;
  }
  return mapping;
}
